### PR TITLE
Create Solution2.java

### PR DESCRIPTION
**Pull request by HisDewness**
- A very basic form of the solution without input validation (for the sake of simplicity)

### CODE REVIEW

**Comment by freddiev4** [comment]
Hey thanks for your contributions. I hope you're learning along the way :smiley: 

I'll take a look at your PRs tomorrow night.

**Comment by HisDewness** [comment]
Anytime, this won't be the last of my contributions if the summer treats me well :+1: 

I'm doing more than just learning, I'm struggling, which is aaaalways a good sign for programmers right? ;)

**Comment by freddiev4** [comment]
Some struggle is definitely good. If you need any help or feedback though, feel free to reach out

**Comment by HisDewness** [comment]
Before I delete the branch, wanted to say I appreciate the offer. Since it's going to be a long summer for me, I might just take you up on that feedback or assistance :)

**Pull request merged**
