### PR TITLE
Update challenge_text.md

### PR DESCRIPTION
**Pull request by vaz-rodrigo**

### CODE REVIEW

**Comment by freddiev4** [comment]
If you plan on updating all of the text in the directories in issue #4, try uploading all the changes to this PR. I'll merge once they're all changed (as it seems that's the direction you're going in)

**Comment by vaz-rodrigo** [comment]
@FreddieV4 Sure, I already fixed 5 from the 9 in there, will probably fix the other 4 later tonight or tomorrow so not sure if you want to put these 5 up now or wait for the other 4.

**Comment by freddiev4** [comment]
If you plan on doing the other 4, I'll just wait :)

Thanks for all your help.

**Comment by vaz-rodrigo** [comment]
Will do them

**Comment by freddiev4** [comment]
Awesome! Fixes Issue #4

**Pull request merged**
