### PR TITLE
Add a note that most naming issues have been resolved, add my name to…

### PR DESCRIPTION
**Pull request by nivintw**
… contributors, fix small formatting issue with one of the contributors names, update the requested format for contributing

### CODE REVIEW

**Comment by freddiev4** [comment]
Just noticed that I merged your previous without double checking something; in Windows `:` is a reserved character and so it may cause some issues with the directory names. The format should be `Challenge xxxx Easy/Intermediate/Hard - Challenge Name`, no?

Rather than 
 `Challenge xxxx Easy/Intermediate/Hard: Challenge Name`

**Comment by nivintw** [comment]
HMM... Windows. 
My thought was that several challenge names have a - somewhere in them... 
If we want, we can just have multple - in them.

**Comment by nivintw** [comment]
Updating now

**Comment by freddiev4** [comment]
Yeah, having multiple `-` is fine; on Windows machines people won't be able to pull the directory due to the `:` character.

**Comment by nivintw** [comment]
Ok, most recent commit for this branch should be good.

**Comment by nivintw** [comment]
The new pull request fixes the directory names to not conflict with Windows.

**Pull request merged**
