### PR TITLE
Create Solution.java

### PR DESCRIPTION
**Pull request by matthires**
Added a solution in java for this problem

### CODE REVIEW

**Comment by matthires** [comment]
Don't know if the lowercase and higher case letters also count ..I mean, if for example "Mm" counts as a consecutive duplicate.  ?

**Comment by freddiev4** [comment]
Yeah the description didn't seem to cover every case for this challenge. I would consider mixes of both uppercase and lowercase to count as consecutive duplicates.

So...

```
MM
mm
Mm
mM
```

For example.

**Comment by freddiev4** [comment]
Also, for this solution and all future solutions, can you make the filenames lowercase? i.e. `solution.java` and not `Solution.java`? Thanks :smile:

**Comment by matthires** [comment]
sorry, I will correct it,thank you!

2016-03-30 23:11 GMT+02:00 Freddie Vargus notifications@github.com:

**Pull request merged**
