### PR TITLE
solutions for easy challenges

### PR DESCRIPTION
**Pull request by doctorBeast**
provided solutions for easy challenge 1 , 2, and 4

### CODE REVIEW

**Comment by Ouss4** [comment]
See the readme file. Solutions must be submitted as solution.py, solution.c, solution.java depending on the language you are using.

**Comment by doctorBeast** [comment]
added solution for easy challenge 5 by the name solution3.py

**Comment by freddiev4** [comment]
@doctorBeast Can you also rename the other files, and push a new commit?

**Comment by Ouss4** [comment]
@doctorBeast why do you use `scanf("%s", &name[0])` instead of `scanf("%s", name)` (same thing in `printf`) ?

**Pull request merged**
