### PR TITLE
Solution1.java

### PR DESCRIPTION
**Pull request by matthires**
my solution of the 1st program

### CODE REVIEW

**Comment by freddiev4** [comment]
Hi. This looks great; but if you could read the **CONTRIBUTING.md** file, you'll see that you need to rename your java file to fit the naming scheme that's been setup. You can just rename it and add another commit to this pull request :smile:

**Comment by matthires** [comment]
Hi! Thank you for your response, I renamed the file.

**Comment by freddiev4** [comment]
@matthires The name of the file is still `Solution of Challenge #0001 [Easy]`

**Comment by nodejsjs** [comment]
@matthires please change the class name to Solution1. Your code will not compile because the file name is Solution1.java and the class name is EasyChallange0001.

**Comment by matthires** [comment]
Sorry for mistakes,I'm new here,but I chnged it! Thank zou for helping :)

2016-03-24 16:21 GMT+01:00 rafid059 notifications@github.com:

**Comment by nodejsjs** [comment]
@matthires hey, no need to be sorry. we are all learning here  :)

**Pull request merged**
